apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatalyakpixelisticfe 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gatalyakpixelisticfe 
    spec:
      containers:
        - name: gatalyakpixelisticfe 
          image: pixelisticacr.azurecr.io/gatalyakpixelisticfe
          ports:
          - containerPort: 80
